# Generated by Django 4.2.1 on 2023-05-24 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_remove_item_comments'),
        ('home', '0002_remove_comments_content_remove_comments_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_comments',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='item_comments',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Item_Comments',
        ),
    ]
