# Generated by Django 4.2.1 on 2023-05-26 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_cartitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date_purchased',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
