# Generated by Django 4.2.1 on 2023-05-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_myorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='myorder',
            name='vendor',
            field=models.TextField(default='user1'),
        ),
    ]
