# Generated by Django 4.2.1 on 2023-05-24 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='item_pics')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('units', models.IntegerField()),
                ('price', models.FloatField()),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.comments')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
